### PR TITLE
[WIP] - Great improvements

### PR DESCRIPTION
**Pull request by markozxuu**
This pr focuses on several changes. The changes will be detailed with tasks for greater organization :)

### Global changes

- [x] Opt for `next-themes` package  to handle  dark-mode 
- [x] Look for a lighter solution than `date-fns` package
- [x] Add font Inter
- [x] Refactoring on the all meta tags
- [x] Create `<Footer />` component
- [x] Create script for generate RSS
- [x] Create route API for generate sitemap
- [x] Create API for set and get views 
- [x] Research an alternative to google analytics: The **use of fathom** was chosen, which is lighter than Google Analytics, in addition to being more focused on privacy. Thank You for the advice @bukinoshita 😸 👍 

### Tasks required for the `/` page

- [x] Adjust styles to tailwindcss

### Tasks required for the `/blog` page

- [x] Improved design
- [x]  Adjust styles to tailwindcss
 
### Tasks required for the `/blog/:post-name`

- [x] Inject `react-notion` styles so that post can render
- [x] Overwriting `notion` styles
- [x] Overwriting `prismjs` styles
- [x] Add font **Cascadia code** for code blocks
- [x] Add `<ViewCounter />` component

### CODE REVIEW

**Comment by markozxuu** [comment]
#### 📝Changed routes:


| [**/**](https://markozxuu-96edfge23.vercel.app/) |
|:-:|
|<a href="https://markozxuu-96edfge23.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/6G3J3MhlbRKwdX1xbxmPYJm1aj0_.png">(view full size)</a> |







Commit 0341f4ff941b8d2b124ab825a820239ad108bb9e (https://markozxuu-96edfge23.vercel.app).

**Comment by bukinoshita** [comment]
Hey, if that helps. Fathom is a great alternative for Google Analytics.

**Comment by markozxuu** [comment]
> Hey, if that helps. Fathom is a great alternative for Google Analytics.

Hi @bukinoshita 👋  thanks for the advice. 

What is the main difference compared to Google Analytics?

**Comment by bukinoshita** [comment]
@markozxuu It's privacy focused, if you want I can share my fathom account with you for your website ☺️

**Comment by markozxuu** [comment]
> @markozxuu It's privacy focused, if you want I can share my fathom account with you for your website ☺️

Thank You, @bukinoshita  !  it is allowed to have analytics of 2 sites?

**Comment by markozxuu** [comment]
Well, all the tasks were accomplished. Time to send this to production 🥰  <3

**Pull request merged**
